### ISSUE TITLE
datasets_ is not find,

### ISSUE THREAD

**Issue by lilijenlisa** [mjmnzg/MFA-LR#1]
in dataloader.py, from datasets_ import Dataset,but datasets_ is not find,can you upload datasets_.py?为什么不上传datasets_.py文件呢？

**Comment by mjmnzg** [comment]
Thanks for your observation, I uploaded such file. Best regards.

**Comment by lilijenlisa** [comment]
Thanks for sharing，likewise，in solvers.py,
from vat import ConditionalEntropyLoss,vat.py is not find, vat is open source libraries?
from utils import plot_tsne, utils.py not have plot_tsne.
Hope you have time to upload it, thank you very much

**Comment by mjmnzg** [comment]
The ConditionalEntropyLoss is located in utils.py, while plot_tsne is not used. Anyway, I updated solvers.py.

**Comment by lilijenlisa** [comment]
Thank you very much for your help, you are such a responsible researcher.  However, I see that the results given by your control experiment seem to be inconsistent with the results in the original paper, such as JAGP with an average accuracy of more than 78% in SEEDIV, but you give 55%. Did you give the result of using the LOSOCV reproduction JAGP method?

**Comment by mjmnzg** [comment]
Please read the paper properly in order to known the experimental design, preprocessing, required conditions, etc. Unfortunately, I can't resolve reading comprehension issues.
